-- AlterTable
ALTER TABLE "BacktestRun" ADD COLUMN "sharpeRatio" DECIMAL(18,6) NOT NULL DEFAULT 0;
ALTER TABLE "BacktestRun" ADD COLUMN "profitFactor" DECIMAL(18,6) NOT NULL DEFAULT 0;
ALTER TABLE "BacktestRun" ADD COLUMN "buyHoldReturnRate" DECIMAL(12,6) NOT NULL DEFAULT 0;
ALTER TABLE "BacktestRun" ADD COLUMN "buyHoldFinalEquity" DECIMAL(18,6) NOT NULL DEFAULT 0;
